"""empty message

Revision ID: 29cdd7e9e9a2
Revises: c8786ad706a7
Create Date: 2020-03-11 15:42:40.903206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29cdd7e9e9a2'
down_revision = 'c8786ad706a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emp_name', sa.String(length=50), nullable=False),
    sa.Column('emp_pass', sa.String(length=150), nullable=False),
    sa.Column('emp_email', sa.String(length=120), nullable=False),
    sa.Column('isAdmin', sa.Boolean(), nullable=True),
    sa.Column('company_name', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['company_name'], ['company.company_name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('employee')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('emp_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('emp_pass', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('emp_email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('isAdmin', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('company_name', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_name'], ['company.company_name'], name='employee_company_name_fkey'),
    sa.PrimaryKeyConstraint('id', name='employee_pkey')
    )
    op.drop_table('temp')
    # ### end Alembic commands ###
