"""empty message

Revision ID: 6dc8b2af42bc
Revises: f88ec4cf69b4
Create Date: 2020-03-11 19:35:45.135057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dc8b2af42bc'
down_revision = 'f88ec4cf69b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(length=50), nullable=False),
    sa.Column('customer_email', sa.String(length=120), nullable=False),
    sa.Column('customer_pno', sa.Integer(), nullable=False),
    sa.Column('customer_gender', sa.String(length=8), nullable=False),
    sa.Column('customer_age', sa.Integer(), nullable=False),
    sa.Column('customer_like', sa.String(length=20), nullable=False),
    sa.Column('company_name', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['company_name'], ['company.company_name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer')
    # ### end Alembic commands ###
