"""empty message

Revision ID: b9b7787a03ae
Revises: 6dc8b2af42bc
Create Date: 2020-03-28 13:30:54.641619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9b7787a03ae'
down_revision = '6dc8b2af42bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('emp_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('emp_pass', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('emp_email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('isAdmin', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('company_name', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_name'], ['company.company_name'], name='employee_company_name_fkey'),
    sa.PrimaryKeyConstraint('id', name='employee_pkey')
    )
    # ### end Alembic commands ###
