"""empty message

Revision ID: c3b8cf57112a
Revises: 830b453fbfbf
Create Date: 2020-04-20 21:53:25.104303

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c3b8cf57112a'
down_revision = '830b453fbfbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('date', sa.TIMESTAMP(), nullable=True))
    op.drop_column('customer', 'Date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('Date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('customer', 'date')
    # ### end Alembic commands ###
