"""empty message

Revision ID: c8786ad706a7
Revises: 
Create Date: 2020-03-06 09:25:23.921532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8786ad706a7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=30), nullable=False),
    sa.Column('company_email', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_email'),
    sa.UniqueConstraint('company_name')
    )
    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emp_name', sa.String(length=50), nullable=False),
    sa.Column('emp_pass', sa.String(length=150), nullable=False),
    sa.Column('emp_email', sa.String(length=120), nullable=False),
    sa.Column('isAdmin', sa.Boolean(), nullable=True),
    sa.Column('company_name', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['company_name'], ['company.company_name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee')
    op.drop_table('company')
    # ### end Alembic commands ###
